import { Document } from 'mongoose'
import { ITagHistoryEntry } from './tag_histories'
import { IDescription } from './descriptions'
export interface IAmortization extends Document {
    company_id: String,
    project_id : String,
    block_id: String,
    lot_id : String,
    realty_id: String,
    team_lead:String,
    team_lead_2:String,
    agent_id:String,
    agent_id_2:String,
    broker_id:String,
    created_by: String,
    updated_by: String,
    reference_code: String,
    payment_id:String,
    buyer_ids: String[],
    monthly_schedules: {
        date: Date,
        amount:Number,
        completed_percent: Number,
        running_balance: Number
    }[],
    monthly_equities: {
        date: Date,
        amount:Number,
        running_balance: Number
    }[],
    payment_ids : String[],
    deleted_payment_ids: String[],
    incentive_id: String,
    area: Number,
    price_per_sqm:Number,
    tcp:Number,
    down_payment:Number,
    down_payment_percent_amount:Number,
    discount_percent:Number,
    discount_percent_amount : Number,
    reservation:Number,
    reservation_date: Date,
    reservation_paid: Boolean,
    lot_condition: String,
    balance:Number,
    monthly:Number,
    equityMonthly:Number,
    commission_sharing: any[],
    overall_commission_percent?: Number,
    overall_commission_amount?: Number,
    terms:Number,
    years: Number,
    remarks: String,
    active?: Boolean,
    total_paid: Number,
    total_paid_percent: Number,
    commission_sharing_locked: Boolean,
    commission_sharing_locked_by: String | null,
    commission_total_released?: Number,
    equityCalculate: Boolean,
    monthlyCalculate: Boolean,
    full_commission: Boolean,
    full_commission_id: String,
    full_commission_by: String,
    tags: String[]
    tagHistory: ITagHistoryEntry[]
    description: String | null,
    descriptionHistory: IDescription[]
}