import { PermissionsMap } from "@/types/permissions";

export interface IBuyerProspect {
    created_by?: string | null,
    first_name: string | null,
    middle_name?: string | null,
    last_name: string | null,
    address?: string | null,
    email: string | null,
    phone_prefix: string | null,
    phone?: string | null,
    land_line?: string | null,
    status?: string | null,
    sourced?: string | null,
    remarks?: string | null,
    type: string | null,
    communicationPreference?: string | null,
    communicationAccount?: string | null,
    otherCommunication?: string | null,
}

export interface IUser {
    company_id: string | null,
    spouse_user_id?: String  | null,
    realty_id?: String | null,
    department_id?: String | null,
    first_name: string | null,
    middle_name?: string | null,
    last_name: string | null,
    address?: string | null,
    region?: string | null,
    province?: string | null,
    city?: string | null,
    barangay?: string | null,
    zip?: string | null,
    gender?: string | null,
    birthdate?: Date,
    civil_status?: string | null,
    password? : string | null,
    email: string | null,
    phone?: string | null,
    account_type: string | null,
    tin?: string | null,
    position?: string | null,
    tin_issuance?: string | null,
    verified?: boolean,
    references: [],
    bank_accounts: [],
    active?: boolean,
    login?: boolean,
    emailGenerated?: boolean,
    roles?: string[],
    override_permissions?: PermissionsMap,
    remarks?: string | null,
}